# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3a797d649ea4bf0810e6f267b1d18dd8c3e5d733b7054d147aec3497f44493d0d575405b2a308d603db008fae37bb15567dfe395e1655fa3056affb019cea54

test:
  secret_key_base: 853b8df6580240a26fcb6718fe262af4027f68b3396f91ee20f9e6519f353ad5b8ccf515ec965d65233878b718398a9c4cf83cce0ce390830b346818b8f51b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
